### PR TITLE
Run Espresso tests on Travis and adding a Rule to log to Travis

### PR DESCRIPTION
**Pull request by rocboronat**
This PR launches the emulator on Travis and runs the Espresso tests on it. It failed some months ago for some misconfiguration but, thanks to @CristianGM and @ferranpons and his work on https://github.com/SchibstedSpain/Leku, we can get that reliable configuration and apply it to Barista.

### CODE REVIEW

**Comment by rocboronat** [comment]
@ferranpons we're having this issue:

`No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received`

Do you have any feedback about this? I guess that the build is blocked by some way... but don't know what to do in that case. Actually, I don't know if the tests are being passed or the emulator is totaly bricked :·/

**Comment by ferranpons** [comment]
@rocboronat looks like the emulator started correctly. What may happen is that connectedDebugAndroidTest took a lot of time to send a log (travis timeout is 10 min) and travis thought that the build stalled or something wrong happened. At this point you have to guess how to solve this problem, by doing a `travis wait` command for more than 10 minutes or sending some kind of log in between your tests or reduce task time somehow.
Leku had that problem, it spend almost 9 minutes to send a log to the console.

I'm sorry about that. 😓

**Comment by rocboronat** [comment]
Hum! Thanks! It gave some light to the problem :·) Let's see what we can do! :·)

**Comment by rocboronat** [comment]
... the Rule doesn't log anything. Letting this PR as it is to avoid losing work, and moving to #83 .

**Pull request closed without merging**
