### PR TITLE
Added View assertion for ImageView showing a Bitmap, with a test.

### PR DESCRIPTION
**Pull request by nmwilk**
Implements https://github.com/SchibstedSpain/Barista/issues/211

### CODE REVIEW

**Comment by nmwilk** [comment]
Ah, I missed that pattern in the tests. Change made as requested. Thanks.

**Comment by rocboronat** [comment]
Wep, just for the information: it should be great to also offer a Bitmap version of `assertHasBackground`. Going to create an issue. Remove it if anyone thinks it's not needed.

**Comment by Sloy** [comment]
Hi! Sorry for being late to the party! We've been away from the project a few months but we're back 💪 

About this feature, I'm worried this might only work for BitmapDrawables and not for images loaded from network or similar. I just tried the matcher by loading the image with Glide and it doesn't work 😞  
`Glide.with(this).load(R.drawable.ic_barista).into(imageView)`

I guess it's because this kind of libraries do transformations on the actual bitmaps, so the expected bitmap will be different from the one loaded into the view.

Not sure how to proceed here 😕

**Comment by rocboronat** [comment]
@Sloy what about explaining it in the error launched by the assertion? You explained so well that all developers should understand it.

**Comment by rocboronat** [comment]
@Sloy the issue is that the methods we're offering right now, `assertHasAnyDrawable(viewId)` and 
`assertHasDrawable(viewId, drawableResId);` are really broad, and in addition, they only work with resources. If you want to test that a given view has a given Bitmap, you can't do it. It's not a big deal for me, because `assertHasAnyDrawable(viewId)` gives a reasonable result, but it's not the ideal one.

In addition, related to our camera intent fake, we could do something to know the result of our mocked camera intent before actually launching it, to write tests to check that the result of a given camera intent actually appears to a given `ImageView`. Right now is a random Bitmap, but it could use a seed or something like that, to enable this kind of tests.

Last words: I think it's not prioritary right now. But let's ask the person who actually invested time on it... @nmwilk is the method `assertHasAnyDrawable()` good enough for you? If not, may you explain why? As we didn't try it in a real environment, we have only the theoric picture of the whole problem... Thanks a lot!

**Comment by nmwilk** [comment]
I don't actually recall the case I was using it for, and I don't have access to that repo anymore. It may have been a test that checks changing an image. E.g. 1/ you choose an image, 2/ the app displays it, 3/ you then choose another image. The test validates step 3 has the new image in.

**Comment by nmwilk** [comment]
So in that case it was working for non-bundled images.

**Comment by Sloy** [comment]
I'm closing this, since we can't be sure it will work on most scenarios. Anyways, this check can also be done with the new `assertAny()` if you need it.

**Comment by Sloy** [comment]
But still, thanks for contributing @nmwilk!

**Pull request closed without merging**
