### PR TITLE
Remove migration guide

### PR DESCRIPTION
**Pull request by EsteveAguilera**
Remove the outdated migration guide

### CODE REVIEW

**Comment by alorma** [comment]
Shouldn't we add a migrate to v3?

**Comment by EsteveAguilera** [comment]
There has been a long time since version 1, so I think we can assume that most projects that were using version 1 did already update to version 2...

**Comment by alorma** [comment]
Makes sense...

Merge it, we should write a migration from 2 to 3. On another task

**Comment by Sloy** [comment]
There isn't much to migrate for v3. Public API contracts and behaviour are maintained :shrug:

**Pull request merged**
