### PR TITLE
Created ViewActionExecutor to reuse performAction() code

### PR DESCRIPTION
**Pull request by jamesbluecrow**

### CODE REVIEW

**Comment by jamesbluecrow** [comment]
@Sloy @rocboronat I've created the class `ViewActionExecutor` just so we can reuse code, thanks to it I've removed the duplication that myself adde when supporting the keyboard actions.

Let me know what you think (and help me out with the name, I'm not sure what to call it, so far `ViewActionExecutor` was the best I could think of.

**Comment by Sloy** [comment]
Haha today I was just doing the same refactor for the similar ugliness that we have in Assertions, but with a different approach. Let me finish it during the weekend and see how they fit together.

**Comment by jamesbluecrow** [comment]
:) Awesome. I just was trying to add the swipe interactions and realized that I would need again this functionality, so I extracted it.
Do you want me to close this? I just did moved the code from one place to another.
Ping me when you finish your refactor so I can take a look too.

**Comment by Sloy** [comment]
For now I would say just copy the code again for your functionality. We know we'll fix it soon enough. 
I have something almost ready, but it might raise discussion. Will ping you ;)

I'd say keep this PR open for now and we'll see later.

**Comment by SmasSive** [comment]
Let's wait for @Sloy proposal but looks great to me since it concentrates the ugliness in just one class! Easier to beautify it later! 💄

**Comment by Sloy** [comment]
@jamesbluecrow check out https://github.com/SchibstedSpain/Barista/pull/198

**Comment by Sloy** [comment]
Hi! I took the liberty of reviving the PR. I updated your code @jamesbluecrow to match the decisions made in #198. I kept the name `performAction`, although it sounds very generic and similar to Espresso's `perform`. I can't think of a name that reflects the real behavior of the method, there's too much magic in there.

After confirming the name and adding a bit of javadoc, I think we can mark this code as ready 😄

**Comment by Sloy** [comment]
No more news is good news. Let's merge it! Thanks for the contribution @jamesbluecrow and sorry for the delay 🎁

**Pull request merged**
