### PR TITLE
Run UI tests on Firebase Test Lab

### PR DESCRIPTION
**Pull request by Sloy**

### CODE REVIEW

**Comment by Sloy** [comment]
This is the list of available devices:

```

┌─────────────┬──────────┬────────────────────┬──────────┬─────────────┬────────────────┬─────────┐
│  DEVICE_ID  │   MAKE   │     MODEL_NAME     │   FORM   │  RESOLUTION │ OS_VERSION_IDS │   TAGS  │
├─────────────┼──────────┼────────────────────┼──────────┼─────────────┼────────────────┼─────────┤
│ D6503       │ Sony     │ Xperia Z2          │ PHYSICAL │ 1920 x 1080 │ 21             │         │
│ D6603       │ Sony     │ Xperia Z3          │ PHYSICAL │ 1920 x 1080 │ 21             │         │
│ E5803       │ Sony     │ Xperia Z5 Compact  │ PHYSICAL │ 1280 x 720  │ 22             │         │
│ F5121       │ Sony     │ Sony Xperia X      │ PHYSICAL │ 1920 x 1080 │ 23             │         │
│ Nexus10     │ Samsung  │ Nexus 10           │ VIRTUAL  │ 2560 x 1600 │ 19,21,22       │         │
│ Nexus4      │ LG       │ Nexus 4            │ VIRTUAL  │ 1280 x 768  │ 19,21,22       │         │
│ Nexus5      │ LG       │ Nexus 5            │ VIRTUAL  │ 1920 x 1080 │ 19,21,22,23    │         │
│ Nexus5X     │ LG       │ Nexus 5X           │ VIRTUAL  │ 1920 x 1080 │ 23,24,25       │         │
│ Nexus6      │ Motorola │ Nexus 6            │ VIRTUAL  │ 2560 x 1440 │ 21,22,23,24,25 │         │
│ Nexus6P     │ Huawei   │ Nexus 6P           │ VIRTUAL  │ 2560 x 1440 │ 23,24,25       │         │
│ Nexus7      │ ASUS     │ Nexus 7 (2012)     │ VIRTUAL  │ 1280 x 800  │ 19,21,22       │         │
│ Nexus9      │ HTC      │ Nexus 9            │ VIRTUAL  │ 2048 x 1536 │ 21,22,23,24,25 │         │
│ athene      │ Motorola │ Moto G4 Plus       │ PHYSICAL │ 1920 x 1080 │ 23             │         │
│ athene_f    │ Motorola │ Moto G4            │ PHYSICAL │ 1920 x 1080 │ 23             │         │
│ condor_umts │ Motorola │ Moto E             │ PHYSICAL │  960 x 540  │ 19             │         │
│ falcon_umts │ Motorola │ Moto G (1st Gen)   │ PHYSICAL │ 1280 x 720  │ 19             │         │
│ flo         │ ASUS     │ Nexus 7 (2013)     │ PHYSICAL │ 1920 x 1200 │ 19,21          │         │
│ flounder    │ HTC      │ Nexus 9            │ PHYSICAL │ 2048 x 1536 │ 21             │         │
│ g3          │ LG       │ LG G3              │ PHYSICAL │ 2560 x 1440 │ 19             │         │
│ hammerhead  │ LG       │ Nexus 5            │ PHYSICAL │ 1920 x 1080 │ 19,21,22,23    │ default │
│ herolte     │ Samsung  │ Galaxy S7          │ PHYSICAL │ 1440 x 2560 │ 23             │         │
│ hlte        │ Samsung  │ Galaxy Note 3 Duos │ PHYSICAL │ 1920 x 1080 │ 19             │         │
│ htc_m8      │ HTC      │ HTC One (M8)       │ PHYSICAL │ 1920 x 1080 │ 19             │         │
│ j5lte       │ Samsung  │ Galaxy J5          │ PHYSICAL │ 1280 x 720  │ 23             │         │
│ lt02wifi    │ Samsung  │ Galaxy Tab 3       │ PHYSICAL │  600 x 1024 │ 19             │         │
│ m0          │ Samsung  │ Samsung Galaxy S3  │ PHYSICAL │ 1280 x 720  │ 18             │         │
│ mako        │ LG       │ Nexus 4            │ PHYSICAL │ 1280 x 768  │ 19,22          │         │
│ osprey_umts │ Motorola │ Moto G (3rd Gen)   │ PHYSICAL │ 1280 x 720  │ 22             │         │
│ p1          │ LG       │ LG G4              │ PHYSICAL │ 1440 x 2560 │ 22             │         │
│ serranolte  │ Samsung  │ Galaxy S4 mini     │ PHYSICAL │  960 x 540  │ 19             │         │
│ shamu       │ Motorola │ Nexus 6            │ PHYSICAL │ 2560 x 1440 │ 21,22,23       │         │
│ t03g        │ Samsung  │ Galaxy Note 2      │ PHYSICAL │ 1280 x 720  │ 19             │         │
│ titan_umts  │ Motorola │ Moto G (2nd Gen)   │ PHYSICAL │ 1280 x 720  │ 19             │         │
│ trelte      │ Samsung  │ Galaxy Note 4      │ PHYSICAL │ 1920 x 1080 │ 22             │         │
│ victara     │ Motorola │ Moto X             │ PHYSICAL │ 1920 x 1080 │ 19             │         │
│ zeroflte    │ Samsung  │ Galaxy S6          │ PHYSICAL │ 2560 x 1440 │ 22             │         │
│ zerolte     │ Samsung  │ Galaxy S6 Edge     │ PHYSICAL │ 2560 x 1440 │ 22             │         │
└─────────────┴──────────┴────────────────────┴──────────┴─────────────┴────────────────┴─────────┘
```

**Comment by Sloy** [comment]
TODO: revert commit 8b5b24a before merging

**Comment by Sloy** [comment]
Tests are passing now, but there is one that seems to be broken.

**Comment by Sloy** [comment]
Oh, they magically passed on the last retry!

**Comment by Sloy** [comment]
According to the docs, the free tier allows 5 test per day on physical devices, and 10 on virtual ones.

**Comment by Sloy** [comment]
Result:
```
┌─────────┬───────────────────────┬────────────────────────────────────┐
│ OUTCOME │    TEST_AXIS_VALUE    │            TEST_DETAILS            │
├─────────┼───────────────────────┼────────────────────────────────────┤
│ Passed  │ Nexus5-22-es-portrait │ 53 test cases passed               │
│ Passed  │ m0-18-es-portrait     │ 53 test cases passed               │
│ Skipped │ Nexus5-18-es-portrait │ Incompatible device/OS combination │
│ Skipped │ m0-22-es-portrait     │ Incompatible device/OS combination │
└─────────┴───────────────────────┴────────────────────────────────────┘
```

**Comment by rocboronat** [comment]
@Sloy what do you think about passing the tests on virtual devices from 19 to 25?

**Comment by Sloy** [comment]
@rocboronat I think that in that case you will be able to test 1 commit per day :rofl:

**Comment by rocboronat** [comment]
@Sloy waaaaw I understood 10 test suites, not 10 tests... woaw.

**Comment by Sloy** [comment]
@rocboronat mmm what do you understand for test suite? And test? xD
From what I get, it's 10 "device executions" in total. 
With 10 devices you can test 1 commit. With 1 device you can test 10 commits. Or that's what I interpret...

**Comment by Sloy** [comment]
Rebased onto master

**Comment by CristianGM** [comment]
So..to have 5 pushes a day we IMHO should just execute it on 2 virtual devices
one with "minSDK"
one with "targetSDK"

**Comment by rocboronat** [comment]
If everyone agrees, let's move forward :·)

**Comment by Sloy** [comment]
Our minSdk is 9, but the oldest version supported by Test Lab is 19.
`¯\_(シ)_/¯`

**Comment by Sloy** [comment]
This time `checkSwipeForward()` failed in 1/2 devices without changing anything on the tests 😢

**Comment by rocboronat** [comment]
We must improve Barista :·) Do you know what's the error launched by Espresso?

**Comment by Sloy** [comment]
It would be nice if the gcloud cli printed it, instead of having to go to the (private) console project.
This is the message:
```
android.support.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: 'is displayed on the screen to the user' doesn't match the selected view.
Expected: is displayed on the screen to the user
     Got: "TextView{id=2131558518, res-name=selected_item, visibility=VISIBLE, width=24, height=57, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, root-is-layout-requested=false, has-input-connection=false, x=528.0, y=822.0, text=2, input-type=0, ime-target=false, has-links=false}"

	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:580)
	at android.support.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:92)
	at android.support.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:56)
	at android.support.test.espresso.ViewInteraction.runSynchronouslyOnUiThread(ViewInteraction.java:184)
	at android.support.test.espresso.ViewInteraction.check(ViewInteraction.java:158)
	at com.schibsted.spain.barista.BaristaAssertions.assertDisplayed(BaristaAssertions.java:37)
	at com.schibsted.spain.barista.sample.ViewPagerTest.checkSwipeForward(ViewPagerTest.java:23)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at android.support.test.internal.statement.UiThreadStatement.evaluate(UiThreadStatement.java:55)
	at com.schibsted.spain.barista.sample.rule.TenRepetitionsActivityTestRule$ActivityStatement.evaluate(TenRepetitionsActivityTestRule.java:248)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
	at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1853)
Caused by: junit.framework.AssertionFailedError: 'is displayed on the screen to the user' doesn't match the selected view.
Expected: is displayed on the screen to the user
     Got: "TextView{id=2131558518, res-name=selected_item, visibility=VISIBLE, width=24, height=57, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, root-is-layout-requested=false, has-input-connection=false, x=528.0, y=822.0, text=2, input-type=0, ime-target=false, has-links=false}"

	at android.support.test.espresso.matcher.ViewMatchers.assertThat(ViewMatchers.java:1053)
	at android.support.test.espresso.assertion.ViewAssertions$2.check(ViewAssertions.java:89)
	at android.support.test.espresso.ViewInteraction$2.run(ViewInteraction.java:170)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by rocboronat** [comment]
Hum... so, Espresso doesn't sent an error with the swipe action but with the assertion... So, he thinkgs that it was done, but it wasn't. HummMMM! Espresso, bad guy.

**Comment by rocboronat** [comment]
@Sloy it could be great if we work on this PR again :·D

**Comment by rocboronat** [comment]
@Sloy as we have Travis running most of the tests at every commit, it's ok for you to close this PR?

**Comment by rocboronat** [comment]
@Sloy feel free to reopen it if you need it :·P

**Comment by rocboronat** [comment]
Reopen! Running tests on Travis' emulator is not reliable. Let's run the tests on Firebase Test Lab!

**Comment by rocboronat** [comment]
Reclosing! I'm running them on a parallel Firebase Test Lab and it's not 100% reliable... closing it and keeping the branch alive.

**Pull request closed without merging**
