### PR TITLE
Replace the .png logo with the .svg one

### PR DESCRIPTION
**Pull request by rocboronat**
Thanks to @DiegoMillanR , our lovely designer! 🏩

### CODE REVIEW

**Comment by Sloy** [comment]
Doesn't seem to work :( 

screen shot 2017-07-13 at 15 24 56

**Comment by rocboronat** [comment]
I see I see. Don't know what happens. I'm looking *ON THE INTERNET*. BTW, solutions are welcome!

**Comment by alorma** [comment]
https://stackoverflow.com/a/21521184

**Comment by rocboronat** [comment]
Pf... let's close the PR 😢

**Pull request closed without merging**
