### PR TITLE
Added assertions for isChecked and isUnchecked

### PR DESCRIPTION
**Pull request by sergiandreplace**
- [x] Created assertions 
- [x] Create tests

### CODE REVIEW

**Comment by rocboronat** [comment]
Great! 🙌

**Comment by rocboronat** [comment]
Hi @sergiandreplace ! Do you want me to create those tests? I'm used to do it, so it's not a problem for me :·)

**Comment by sergiandreplace** [comment]
Tests created!

**Comment by rocboronat** [comment]
Thanks @sergiandreplace ! Big contribution, and really well tested! :·)

**Pull request merged**
