### PR TITLE
Move one class and delete another one to keep the house clean

### PR DESCRIPTION
**Pull request by rocboronat**
This PR is just to keep the house clean. I found some issues when preparing some slides to talk about Barista... and here's the PR 🥇

### CODE REVIEW

**Comment by rocboronat** [comment]
BTW, passed tests on local and they worked 💪

**Comment by Sloy** [comment]
Question: Is this class a public API?

Because changing the package of a public API will break the client implementation.

**Comment by rocboronat** [comment]
@Sloy nope, it's just an internal class. It's used by the public API `BaristaScrollActions.scrollTo()`.

**Comment by Sloy** [comment]
Good!

**Comment by rocboronat** [comment]
🎉

**Pull request merged**
