### PR TITLE
Clarify how to use the custom assertions message

### PR DESCRIPTION
**Pull request by rocboronat**
As @Sloy explained at #255, the agreed readme could be improved. This PR does it.

Now, the project's readme will explain the custom assertion message feature by example.

### CODE REVIEW

**Comment by rocboronat** [comment]
@Sloy @SmasSive do you have any thoughts?

**Comment by rocboronat** [comment]
@Sloy @SmasSive do you have any thoughts?

**Comment by Sloy** [comment]
I'm trying to approve but GitHub engineers are having a bad time right now.

**Comment by Sloy** [comment]
I'm trying to approve but GitHub engineers are having a bad time right now.

**Comment by Sloy** [comment]
I'm trying to approve but GitHub engineers are having a bad time right now.

**Comment by Sloy** [comment]
I'm trying to approve but GitHub engineers are having a bad time right now.

**Comment by rocboronat** [comment]
Noice!

**Pull request merged**
