### PR TITLE
Assert content description

### PR DESCRIPTION
**Pull request by alorma**
This PR tries to fix: https://github.com/SchibstedSpain/Barista/issues/304

Add content description assertion, working on images, texts... any view :D

### CODE REVIEW

**Comment by alorma** [comment]
@EsteveAguilera ?

**Comment by EsteveAguilera** [comment]
What about adding tests to check that it fails when the view has no content description?

**Comment by EsteveAguilera** [comment]
Oh, and I've removed the content description on an ImageView to check that the tests are failing, and I've got a confusing error message:

`didn't match condition (with no content description)`

Shouldn't it be `didn't match condition (with content description)`?

**Comment by alorma** [comment]
Updated!

**Comment by EsteveAguilera** [comment]
👏 @alorma, now it's a 👍for me!

**Pull request merged**
