### PR TITLE
BaristaSpinnerInteractions converted to kotlin

### PR DESCRIPTION
**Pull request by jamesbluecrow**

### CODE REVIEW

**Comment by jamesbluecrow** [comment]
Yes I did. In any case, doesn't Travis do it too?

**Comment by rocboronat** [comment]
Nope @jamesbluecrow, Travis doesn't pass the espresso tests. They are flaky on the emulator that runs on Travis, we don't know why. We're open to PRs to fix it, too 😅

**Comment by jamesbluecrow** [comment]
hahaha. I don't have experience with Travis yet, but if I find time I'll take a look. 
Have we considered on using Firebase test lab? At Trov we use bitrise and connecting it to Test lab is very easy and it works very well.

**Comment by Sloy** [comment]
We tried it some time ago, but didn't work too well either: https://github.com/SchibstedSpain/Barista/pull/5

Maybe we can take another look into it, see if we missed something or it has improved.

**Comment by jamesbluecrow** [comment]
Yes I did run them locally too.
Btw, @Sloy @rocboronat I see that all the test are written in java, is it ok if we convert them to kotlin, or at least the new ones we write them in kotlin?

**Comment by rocboronat** [comment]
IMHO, Kotlin is not really needed or useful in the tests, but I'm OK with both Java or Kotlin ones :·)

**Comment by jamesbluecrow** [comment]
cool, I asked just because it seems that I'm using the same formatter for kotlin but not for java so it is annoying to format the code manually.

**Comment by rocboronat** [comment]
Totally :·/ We opened an issue to fix it: #154

By the way, the most similar codestyle right now is the Square one: https://github.com/square/java-code-styles

**Comment by Sloy** [comment]
@jamesbluecrow right now I see one motive to keep the tests in java: they're or way of making sure the public api is 100% java compatible. (Static methods, overloaded method parameters, etc). Although I'm sure at some point we will have to migrate them, I'm not sure if we're there yet. 

It's a personal opinion though, we haven't really discussed it at all yet.

**Comment by rocboronat** [comment]
Oh, it's a good reason, never thought about it.

**Comment by jamesbluecrow** [comment]
I didn't think about that and it makes a lot of sense, smart thinking @Sloy 👍

**Pull request merged**
