### PR TITLE
Run upload task on PRs also

### PR DESCRIPTION
**Pull request by Sloy**
Using dry run and fake auth, of course.

This solves the problems found at #34, where some tasks are only run when releasing and might fail after a new PR has been merged already.

The original idea was to run the task that failed in my case (`: library:mavenAndroidJavadocs`), but I think using the dryRun feature of the publishing plugin is better. This way we make sure all release tasks are executed except for the upload itself.

### CODE REVIEW

**Comment by rocboronat** [comment]
Hey Rafa! Just seen the new .sh script but... how's that related with the main build at Travis? I mean, why Travis will run it?

**Comment by Sloy** [comment]
@rocboronat you're right, I tried a few thing locally and didn't put them together properly 😂 

Now it should be fine. I changed the task `check` for `build`, I didn't see a reason not to. That way we make sure everything is working, right?

**Comment by rocboronat** [comment]
Wait... now, we're uploading to bintray at every build? That's what we want?

```groovy
script:
  - scripts/bintrayUpload.sh`
```

**Comment by rocboronat** [comment]
I think that we should call `scripts/build.sh` instead of `scripts/bintrayUpload.sh` at `script`

**Comment by Sloy** [comment]
Today's not my day. Check again.
No more github for me until tomorrow 💀

**Comment by rocboronat** [comment]
More by the ways... why not just call 

`./gradlew build bintrayUpload -PbintrayUser=dryrun-user -PbintrayKey=dryrun-key -PdryRun=true` at `script` ? It will save the need of opening another file to understand what's done on script. I mean, it's just one line... no need to add complexity there.

**Comment by Sloy** [comment]
However you like. I did it in another file for consistency with the other script.

**Comment by rocboronat** [comment]
I guess that it's to follow the style of `bintrayUpload.sh` ...? The thing is that hiding the magic of uploading to bintray is something good, cos it sounds that it will be the same on every project that works with this plugin, but knowing what's done on the build phase will be different for different projects. I mean, knowing how's done the upload is not important, but knowing what's happening on the `script` phase is interesting to be catchy.

By the way, feel free, is just an opinion and the change is very easy to do :·D

**Comment by rocboronat** [comment]
Great! Thanks @Sloy :·) Feel free to squash and merge it! :·)

**Pull request merged**
