### PR TITLE
Update gradle and Build Tools

### PR DESCRIPTION
**Pull request by rocboronat**
Android Studio warned me about living in the past. This PR fixes it.

In addition, as one build crashed while waiting for an emulator (that we don't use yet), this PR also avoids waiting for it.

### CODE REVIEW

**Comment by Sloy** [comment]
Wow didn't know we had an emulator there!

**Comment by Sloy** [comment]
Hey @rocboronat the build failed. I can't check the log right now on my phone sorry :(

**Comment by rocboronat** [comment]
Yes yes, I see! :·) Going to fix it...

**Comment by rocboronat** [comment]
Strange. It seems that `com.android.support.test.uiautomator:uiautomator-v18:2.1.2` had a dependency with `com.android.support:recyclerview-v7:21.0.3`. Well... happy to learn! :tada:

**Pull request merged**
